### ISSUE TITLE
contributte/di extended but not required in composer

### ISSUE THREAD

**Issue by finwe** [contributte/messenger#10]
When installed per documentation in a plain nette project, compiling the DI container ends with `Class "Contributte\DI\Extension\CompilerExtension" not found` as `contributte/di` is not required in the package `require` composer.json section.

**Comment by finwe** [comment]
Can prepare a PR if adding the library is the preferred solution. Which version should be required?

**Comment by f3l1x** [comment]
Please drop contributte/di usage, thank you.

**Comment by finwe** [comment]
@f3l1x I'm not sure I understand correctly. Should I stop using contributte/di, or add contributte/di to composer.json, and if so, which version? :)

**Comment by f3l1x** [comment]
I mean, remove `Contributte\DI\Extension\CompilerExtension` and extends from nette/di directly.
