### ISSUE TITLE
Configuration schema does not allow wildcard from the example documentation

### ISSUE THREAD

**Issue by finwe** [contributte/messenger#11]
Using

    routing:
        *: [redis]

in config ends with `Failed assertion #0 for key of item 'messenger › routing › *' with value '*'` as the expected key for the routing is `$expectClass` which allows class or interface names only.

Was the wildcard routing present at any point and the validation can be altered, or is the example in the documentation only a hint for the future?

**Comment by f3l1x** [comment]
It's bug. It should be working.
